### ISSUE TITLE
Error message while grabbing metadata

### ISSUE THREAD

**Issue by LulzRose** [NoMod-Programming/PearsonEbookDownloader#16]
python3 downloader.py 97951
Downloading book id 97951. Please open an issue on GitHub if this book id is incorrect.
Downloading metadata and eText information...
Traceback (most recent call last):
  File "downloader.py", line 225, in <module>
    main(sys.argv[1])
  File "downloader.py", line 92, in main
    bookeditionid=bookInfo['bookEditionID']
TypeError: 'NoneType' object is not subscriptable

**Comment by NoMod-Programming** [comment]
Hi, are you sure this book id exists? It seems that no book data exists for it that the downloader can reach. Do you have more of the book URL?

**Comment by kinto0** [comment]
I get the same error with book id `9780135635414`. It's from etext-ise.pearson.com. Is that supported? Thanks!

**Comment by K-zhao** [comment]
@kyleai I have the same issue with etext-ise.pearson.com - I'm not entirely sure where to find the book URL or ID - anything that looks like it could be exceeds the 5-6 digit length that was mentioned in the instructions.

**Comment by NoMod-Programming** [comment]
Unfortunately, the etext-ise.pearson.com ebooks are currently unsupported by the downloader. I'm sorry say that I don't know of any workaround for that.

Best of luck,
NoMod-Programming

**Comment by K-zhao** [comment]
Just for future reference, i was able to pull the full pdf file by doing the following:

1. Download the ebook on your phone through the Pearson app.
2. Find the folder root/data/data/com.pearsoned.etext2he/AQUA/ (Worked for android, not sure for iOS, not sure if root access is needed)
3. Copy .zip file onto computer and rename into .epub. At this point you can use any ebook program to view, though step 4 would be needed for .pdf
4. Find any service/program that can convert .epub into .pdf 
I've noticed bookmarks carry over through all of these conversions which is a pleasant surprise.

@kyleai This might of use for you.
