### ISSUE TITLE
Error while downloading ebook

### ISSUE THREAD

**Issue by mattsblack** [NoMod-Programming/PearsonEbookDownloader#18]
I got this error while downloading from Pearson Realize:
Traceback (most recent call last):
  File "downloader.py", line 225, in <module>
    main(sys.argv[1])
  File "downloader.py", line 92, in main
    bookeditionid=bookInfo['bookEditionID']
TypeError: 'NoneType' object is not subscriptable

my book id was: 1007141

I think maybe the id was too long? 
I also tried to use the GitHub pages version of this with the same id and I got this error:
[{
  "userBookTOList" : [ null ]
}]

**Comment by NoMod-Programming** [comment]
What's your book's ID?

**Comment by mattsblack** [comment]
1007141
