### ISSUE TITLE
Error when gathering metadata

### ISSUE THREAD

**Issue by nicologian** [NoMod-Programming/PearsonEbookDownloader#23]
Im getting this error, how do I fix this?

Traceback (most recent call last):
  File "downloader.py", line 225, in <module>
    main(sys.argv[1])
  File "downloader.py", line 115, in main
    urllib.request.urlretrieve(getPageUrl(bookInfo['pdfCoverArt'], isCover="Y"), os.path.join(pdfDownloadDir, "0000 - cover.pdf"))
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by nicologian** [comment]
BookId used: 129134

**Comment by NoMod-Programming** [comment]
Unfortunately, all books are returning a 404 error for each page at the moment, and I'm not able to devote much time to figuring it out. It seems like the downloader requires authentication in order to work, so that'll be something to look into once I've got more time.
