### ISSUE TITLE
can't download math textbook

### ISSUE THREAD

**Issue by mattsblack** [NoMod-Programming/PearsonEbookDownloader#31]
whenever I try to download this textbook I get this error: 
Downloading book id 78293. Please open an issue on GitHub if this book id is incorrect.
Downloading metadata and eText information...
Traceback (most recent call last):
  File "downloader.py", line 225, in <module>
    main(sys.argv[1])
  File "downloader.py", line 115, in main
    urllib.request.urlretrieve(getPageUrl(bookInfo['pdfCoverArt'], isCover="Y"), os.path.join(pdfDownloadDir, "0000 - cover.pdf"))
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

the book id is 78293. 
the link that I found the book id is: https://spectrum.pearsoned.com/api/v3/annotations/bookId/78293/courseId/5520160?annotationType=Bookmark&limit=100&offset=0

I found that link through the network tab in the inspect element settings.

**Comment by itisraffycame** [comment]
I have the exact same problem and I don't know what to do. Were you able to resolve?

**Comment by mattsblack** [comment]
I found a temporary solution. I used a script to screenshot all of the textbook pdf pages. It is in a repository in my profile.
